### ISSUE TITLE
Clean up and document the `roadmap` script

### ISSUE THREAD

**Issue by jonschz** [isledecomp/reccmp#31]
- [ ] Add tests
- [ ] Improve the documentation of the arguments
- [ ] Add example calls to the README

            Some comments:

First off: it must be said that this script is a little rough, and you could argue that it lacks a clear purpose. My reason for creating it was to identify smartheap functions in ISLE (see `library_smartheap.h`). It was helpful to see where there was a gap between known functions. The main `asmcmp` script doesn't show _everything_.

The `--order` feature came after. It makes an educated guess about how to order the modules in the makefile. For a given module, MSVC will put certain functions a long way from its neighbors. We try to remove the outliers to get the best average of where the module's contents should sit. You can compute this estimate for things other than functions, too. For example, vtables: `--order VTA`. AFAIK we haven't applied this information to `LEGO1` but since we are coming to the end of new functions, maybe now is the time.

As far as tests: aside from one to just make sure it runs, maybe we could add some around the display features? For example: there is a bug in `get_cmakefiles_prefix` since I am now using ninja to build and the slashes go the other way. I think we could use `pathlib` to normalize this.

On line 244: `print(prefix)`. I forget why this is there and it can probably be taken out.

_Originally posted by @disinvite in https://github.com/isledecomp/reccmp/issues/30#issuecomment-2529098001_

**Comment by disinvite** [comment]
I've been using `roadmap` regularly as a way to assess the impact of various code changes. It pretty conveniently dumps all the entities out to a file, so I just diff the text output from before and after the change.

- [ ] Add an option to display absolute address instead of seg:offset.
- [ ] We should reassess the problem I described in `get_cmakefiles_prefix`. It's not a requirement for reccmp projects to use CMake so this may not be relevant in every case.
- [ ] To calculate the difference in position between orig and recomp addr, we have to check whether they are in equivalent sections in each binary. The sections may not be aligned or there may be extra ones, as was the case with the Smacker lib in LEGO1. All we have to go on is the section name. This is okay if they are the conventional names like `.text`, but is there something better we should do instead?
